# Generated by Django 3.2.3 on 2021-05-21 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='mymodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('age', models.IntegerField(default=0)),
                ('email', models.CharField(max_length=60)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
